### ISSUE TITLE
500 error when registering

### ISSUE THREAD

**Issue by uskudarli** [kahyabatuhan/swe-573#10]
I tried to register and got the following error:

500 Error Occurred. Server error, we have been alerted, please try again later.

**Comment by kahyabatuhan** [comment]
It was due to gmail less secure app access turned off.
I turned on gmail less secure app access to solve the issue
Registration should be working properly

**Comment by kahyabatuhan** [comment]
gmail access is required to send activation emails during registration.
In case, gmail blocks the app access again, please login by username: visitor and password:123
thank you
